baseURL: http://example.org/
languageCode: en-us
title: Sugar Candy Gallery
theme: sugar-candy-gallery
params:
  copyright: >-
    Copyright &copy; 2022 All Rights Reserved. &mdash; Designed with love by
    [Untree.co](https://untree.co) &bullet; [License](https://untree.co/license)
  description: >-
    Write an awesome description for your new site here. You can edit this line
    in _config.yml. It will appear in your document head meta (for Google search
    results) and in your feed.xml site description.
  author: John Doe
  instagram: null
  pinterest: https://twitter.com/quiqrapp
  facebook: null
  twitter: https://twitter.com/quiqrapp
  menu:
    - name: About
      url: page/about/
    - name: Contact
      url: page/contact
    - name: Other gallery
      url: page/other
  font1: Cardo
  font2: Inter
  color_text_1a: '#777'
  color_text_1b: '#fff'
  color_text_2a: '#FF5677'
  color_text_2b: '#ff3058'
  color_bg: black
markup:
  goldmark:
    renderer:
      unsafe: true
