baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Sugar Candy Gallery'
theme: 'sugar-candy-gallery'
params:
  copyright: "Copyright &copy; 2022 All Rights Reserved. &mdash; Designed with love by [Untree.co](https://untree.co) &bullet; [License](https://untree.co/license)"

  description: >- # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
  author: John Doe

  instagram: #
  pinterest: #
  facebook: #
  twitter: https://twitter.com/quiqrapp

markup:
  goldmark:
    renderer:
      unsafe: true

